apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: ssos.jenkins.io
spec:
  additionalPrinterColumns:
  - JSONPath: .metadata.creationTimestamp
    description: |-
      CreationTimestamp is a timestamp representing the server time when this object was created. It is not guaranteed to be set in happens-before order across separate operations. Clients may not set this value. It is represented in RFC3339 form and is in UTC.

      Populated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata
    name: Age
    type: date
  group: jenkins.io
  names:
    kind: SSO
    listKind: SSOList
    plural: ssos
    shortNames:
    - sso
    singular: sso
  scope: Namespaced
  version: v1
  versions:
  - name: v1
    served: true
    storage: true